language: python
python:
  - "3.6"
#  - "pypy3"

# command to install dependencies
before_install:
  - sudo apt-get -y install python3-distutils-extra
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
- nosetests test/*